config/routes.rb
Rails.application.routes.draw do
  resources :certificates
  resources :transports
  resources :facilities
  resources :equipment
  resources :roles
  resources :courses
  resources :course_titles
  devise_for :users, controllers: {
          sessions: 'users/sessions',
          registrations: 'users/registrations'
        }
  # devise_for :users
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/transport.rb
class Transport < ApplicationRecord
  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :description, presence: true
end

app/controllers/transports_controller.rb
class TransportsController < ApplicationController
  before_action :set_transport, only: [:show, :edit, :update, :destroy]

  # GET /transports
  # GET /transports.json
  def index
    @transports = Transport.all
  end

  # GET /transports/1
  # GET /transports/1.json
  def show
    if @transport.added_by
      @adder = User.find(@transport.added_by)
    end
    if @transport.changed_by
      @changer = User.find(@transport.changed_by)
    end
    if @transport.archived_by
      @archiver = User.find(@transport.archived_by)
    end
  end

  # GET /transports/new
  def new
    @transport = Transport.new
  end

  # GET /transports/1/edit
  def edit
  end

  # POST /transports
  # POST /transports.json
  def create
    @transport = Transport.new(transport_params)
    @transport.added_by = current_user.id
    @transport.added_at = Time.now

    respond_to do |format|
      if @transport.save
        format.html { redirect_to @transport, notice: 'Transport was successfully created.' }
        format.json { render :show, status: :created, location: @transport }
      else
        format.html { render :new }
        format.json { render json: @transport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transports/1
  # PATCH/PUT /transports/1.json
  def update
    @transport.changed_by = current_user.id
    @transport.changed_at = Time.now
    
    respond_to do |format|
      if @transport.update(transport_params)
        format.html { redirect_to @transport, notice: 'Transport was successfully updated.' }
        format.json { render :show, status: :ok, location: @transport }
      else
        format.html { render :edit }
        format.json { render json: @transport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transports/1
  # DELETE /transports/1.json
  def destroy
    # @transport.destroy
    # respond_to do |format|
    #   format.html { redirect_to transports_url, notice: 'Transport was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transport
      @transport = Transport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transport_params
      params.require(:transport).permit(:name, :description, :added_by, :added_at, :changed_by, :changed_at, :archived_by, :archived_at)
    end
end

app/helpers/transports_helper.rb
module TransportsHelper
end

app/views/transports/_form.html.erb
<%= form_with(model: transport, local: true) do |form| %>
  <% if transport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transport.errors.count, "error") %> prohibited this transport from being saved:</h2>

      <ul>
      <% transport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transports/edit.html.erb
<h1>Editing Transport</h1>

<%= render 'form', transport: @transport %>

<%= link_to 'Show', @transport %> |
<%= link_to 'Back', transports_path %>

app/views/transports/index.html.erb
<h3>Transports</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Added by</th>
      <th>Added at</th>
      <th>Changed by</th>
      <th>Changed at</th>
      <th>Archived by</th>
      <th>Archived at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transports.each do |transport| %>
      <tr>
        <td><%= transport.name %></td>
        <td><%= transport.description %></td>
        <td><%= transport.added_by %></td>
        <td><%= transport.added_at %></td>
        <td><%= transport.changed_by %></td>
        <td><%= transport.changed_at %></td>
        <td><%= transport.archived_by %></td>
        <td><%= transport.archived_at %></td>
        <td><%= link_to 'Show', transport %></td>
        <td><%= link_to 'Edit', edit_transport_path(transport) %></td>
        <td><%= link_to 'Destroy', transport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transport', new_transport_path %>

app/views/transports/new.html.erb
<h1>New Transport</h1>

<%= render 'form', transport: @transport %>

<%= link_to 'Back', transports_path %>

app/views/transports/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @transport.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @transport.description %>
</p>

<p>
  <strong>Added by:</strong>
  <%= @transport.added_by %>
</p>

<p>
  <strong>Added at:</strong>
  <%= @transport.added_at %>
</p>

<p>
  <strong>Changed by:</strong>
  <%= @transport.changed_by %>
</p>

<p>
  <strong>Changed at:</strong>
  <%= @transport.changed_at %>
</p>

<p>
  <strong>Archived by:</strong>
  <%= @transport.archived_by %>
</p>

<p>
  <strong>Archived at:</strong>
  <%= @transport.archived_at %>
</p>

<%= link_to 'Edit', edit_transport_path(@transport) %> |
<%= link_to 'Back', transports_path %>