config/routes.rb
Rails.application.routes.draw do
  resources :certificates
  resources :transports
  resources :facilities
  resources :equipment
  resources :roles
  resources :courses
  resources :course_titles
  devise_for :users, controllers: {
          sessions: 'users/sessions',
          registrations: 'users/registrations'
        }
  # devise_for :users
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/certificate.rb
class Certificate < ApplicationRecord
  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :duration_in_years, numericality: {greater_than_or_equal_to: 0, less_than: 20}
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  before_action :set_certificate, only: [:show, :edit, :update, :destroy]

  # GET /certificates
  # GET /certificates.json
  def index
    @certificates = Certificate.all
  end

  # GET /certificates/1
  # GET /certificates/1.json
  def show
  end

  # GET /certificates/new
  def new
    @certificate = Certificate.new
  end

  # GET /certificates/1/edit
  def edit
  end

  # POST /certificates
  # POST /certificates.json
  def create
    @certificate = Certificate.new(certificate_params)

    respond_to do |format|
      if @certificate.save
        format.html { redirect_to @certificate, notice: 'Certificate was successfully created.' }
        format.json { render :show, status: :created, location: @certificate }
      else
        format.html { render :new }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /certificates/1
  # PATCH/PUT /certificates/1.json
  def update
    respond_to do |format|
      if @certificate.update(certificate_params)
        format.html { redirect_to @certificate, notice: 'Certificate was successfully updated.' }
        format.json { render :show, status: :ok, location: @certificate }
      else
        format.html { render :edit }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certificates/1
  # DELETE /certificates/1.json
  def destroy
    @certificate.destroy
    respond_to do |format|
      format.html { redirect_to certificates_url, notice: 'Certificate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certificate
      @certificate = Certificate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def certificate_params
      params.require(:certificate).permit(:name, :duration_in_years)
    end
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/views/certificates/_form.html.erb
<%= form_with(model: certificate, local: true) do |form| %>
  <% if certificate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(certificate.errors.count, "error") %> prohibited this certificate from being saved:</h2>

      <ul>
      <% certificate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :duration_in_years %>
    <%= form.text_field :duration_in_years %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/certificates/edit.html.erb
<h1>Editing Certificate</h1>

<%= render 'form', certificate: @certificate %>

<%= link_to 'Show', @certificate %> |
<%= link_to 'Back', certificates_path %>

app/views/certificates/index.html.erb
<h1>Certificates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Duration in years</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @certificates.each do |certificate| %>
      <tr>
        <td><%= certificate.name %></td>
        <td><%= certificate.duration_in_years %></td>
        <td><%= link_to 'Show', certificate %></td>
        <td><%= link_to 'Edit', edit_certificate_path(certificate) %></td>
        <td><%= link_to 'Destroy', certificate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Certificate', new_certificate_path %>

app/views/certificates/new.html.erb
<h1>New Certificate</h1>

<%= render 'form', certificate: @certificate %>

<%= link_to 'Back', certificates_path %>

app/views/certificates/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @certificate.name %>
</p>

<p>
  <strong>Duration in years:</strong>
  <%= @certificate.duration_in_years %>
</p>

<%= link_to 'Edit', edit_certificate_path(@certificate) %> |
<%= link_to 'Back', certificates_path %>