config/routes.rb
Rails.application.routes.draw do
  resources :certificates
  resources :transports
  resources :facilities
  resources :equipment
  resources :roles
  resources :courses
  resources :course_titles
  devise_for :users, controllers: {
          sessions: 'users/sessions',
          registrations: 'users/registrations'
        }
  # devise_for :users
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/certificate.rb
class Certificate < ApplicationRecord
  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :duration_in_years, numericality: {greater_than_or_equal_to: 0, less_than: 20}
end

app/models/course.rb
class Course < ApplicationRecord
  # include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks

  belongs_to :course_title
  validates :duration, presence: true
  validates :fees, numericality: true

  def as_indexed_json(options={})
    {
      "course_title_name": course_title.name,
      "course_title_description": course_title.description,
      "duration": duration,
      "fees": fees,
      "start_date": start_date,
      "finish_date": finish_date
    }
  end

end

app/models/course_title.rb
class CourseTitle < ApplicationRecord

  # include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks

  has_many :courses
  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :description, presence: true

  # after_save :index_courses_in_elasticsearch


  def as_indexed_json(options = {})
    self.as_json(
      only: [:id, :name, :description, :active]
    )
  end  

  private 
  def index_courses_in_elasticsearch
    courses.find_each { |course| course.__elasticsearch__.index_document }
  end

end

app/models/equipment.rb
class Equipment < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :asset_tag, presence: true, uniqueness: {case_sensitive: false}
end

app/models/facility.rb
class Facility < ApplicationRecord
  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :description, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
  validates :name, :description, presence: true, uniqueness: {case_sensitive: false}
  before_save {|role|role.name = role.name.downcase}
end

app/models/transport.rb
class Transport < ApplicationRecord
  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  # def new
  #   @role = Role.new
  # end

  # GET /roles/1/edit
  # def edit
  # end

  # POST /roles
  # POST /roles.json
  # def create
  #   @role = Role.new(role_params)

  #   respond_to do |format|
  #     if @role.save
  #       format.html { redirect_to @role, notice: 'Role was successfully created.' }
  #       format.json { render :show, status: :created, location: @role }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @role.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  # def update
  #   respond_to do |format|
  #     if @role.update(role_params)
  #       format.html { redirect_to @role, notice: 'Role was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @role }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @role.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /roles/1
  # DELETE /roles/1.json
  # def destroy
  #   @role.destroy
  #   respond_to do |format|
  #     format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/helpers/course_titles_helper.rb
module CourseTitlesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/transports_helper.rb
module TransportsHelper
end

app/views/layouts/_footer.html.erb
<section class="footer">
      <div class="container">
	  <div class="row">
        <div class="col-lg-3">
		
          <h5 class="title">About Us</h5>
         
          <p> To assist business organization by consultancy, Sukkur IBA started Training and Development Department in 2008, whose aim is to provide technical and managerial skills development training programme to corporate sector as well as public sector employees.  </p>
          <a href="http://facebook.com/sibaedc/" target="_blank" class="read-more">Read More »</a> </div>
         <div class="col-xs-12 col-sm-3 service">
          <h5 class="title">Quick Links</h5>
         <ul>
				<a href="facilities.html"><li>Facilities</li></a>
				<a href="Trainers.html"><li>Trainers</li></a>
				<li>Services</li>
				<a href="about-us.html"><li>About US</li></a>
				<a href="contactus.html"><li>Contact Us</li></a>
        </ul>
        </div>
        <div class="col-lg-3">
          <h5 class="title">Our Service Areas</h5>
          <ul>
             <li>Training and Development</li>
            <li>Customized Training</li>
            <li>Training Need Analysis</li>
            <li>Executive Coaching</li>  
            
            <li>CSS Preparatory Classes</li>
            <li>Rental Resources</li>
          </ul>
        </div>
        <div class="col-lg-3">
          <h5 class="title">Get in Touch</h5>
          <p> <i class="fas fa-map-marker"></i> <span>Sukkur IBA Executive Development Center
            Sukkur IBA Campus II By Pass Road Sukkur </span></p>
          <p> <i class="fas fa-phone"></i> <span>(071) 45644118   </span></p>
          <p> <i class="fas fa-envelope"></i> <span><%= mail_to 'edc@iba-suk.edu.pk' %> </span></p>
          <ul class="social">
            <li><a href="http://facebook.com/sibaedc/" target="_blank" class="hvr-radial-out "><i class="fas fa-facebook"></i></a></li>
            <li><a href="http://twitter.com/sukkur_iba_edc/" target="_blank" class="hvr-radial-out "><i class="fas fa-twitter"></i></a></li>
            <li><a href="https://plus.google.com/110613141576926898851" target="_blank" class="hvr-radial-out "><i class="fas fa-google-plus"></i></a></li>
          </ul>
        </div>
		</div>
      </div>
      <div class="copyright">
        <div class="container">
		<div class="row">
          <div class="col-lg-12 ">
            <p> Copyright © Sukkur IBA Executive Development Center - EDC 2017. All rights reserved. </p>
          </div>
		  </div>
        </div>
      </div>
    </section>

app/views/layouts/_header.html.erb
<div id="header">
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<a class="navbar-brand" href="<%= root_url %>">EDC</a>
		<button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
		aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="collapsibleNavId">
		<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
			<!-- <li class="nav-item active">
				<a class="nav-link" href="<%= root_url %>">Home <span class="sr-only">(current)</span></a>
				</li> -->
				<% if user_signed_in? %>
				<li class="nav-item">
					<%= link_to 'Titles', course_titles_url, class: "nav-link" %>
				</li>
				<li class="nav-item">
					<%= link_to 'Courses', courses_url, class: "nav-link" %>
				</li>
				<!-- <li class="nav-item">
					<%= link_to 'Certificates', certificates_url, class: "nav-link" %>
				</li> -->
				<li class="nav-item">
					<%= link_to 'Equipment', equipment_index_url, class: "nav-link" %>
				</li>
				<li class="nav-item">
					<%= link_to 'Facility', facilities_url, class: "nav-link" %>
				</li>
				<li class="nav-item">
					<%= link_to 'Transport', transports_url, class: "nav-link" %>
				</li>
				<li class="nav-item">
					<!-- <a class="nav-link" href="#">Link1</a> -->
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<i class="fas fa-user text-primary">&nbsp;</i>
						User
					</a>
					<div class="dropdown-menu" aria-labelledby="dropdownId">
						<%= link_to edit_user_registration_path, class: "dropdown-item" do %>
						<i class="fas fa-user-edit text-success">&nbsp;</i>Profile
						<% end %>
						<%= link_to destroy_user_session_path, method: "delete", data: {confirm: "Are you sure?"}, class: "dropdown-item"  do %>
						<i class="fa fa-trash text-danger" aria-hidden="true"></i>
						Signout
						<% end %>
					</div>
				</li>
				<% else %>
					<li class="nav-item">
						<%= link_to new_user_session_path, class: "nav-link" do %>
						<i class="fas fa-sign-in-alt text-primary">&nbsp;</i>
						Signin
						<% end %>
					</li>
				<% end %>

				<!-- <form class="form-inline my-2 my-lg-0">
					<input class="form-control mr-sm-2" type="text" placeholder="disable ...">
					<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
				</form> -->
			</ul>
		</div>
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EDC - IBA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>

  <body>
    <div class="container-fluid">
        <%= render "layouts/header" %>
    </div>
        <div class="container">
          <p id="alert" class="text-warning"><%= alert if alert %></p>
          <p id="notice" class="text-primary"><%= notice if notice %></p>
          <%= yield %>
      </div>
        
    <div class="container-fluid">
        <%= render "layouts/footer" %>    
    </div>
		
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
  </body>
</html>